---
development:
  cloud_name: hhyoi8noh
  api_key: '797163287459554'
  api_secret: AoduUAGnF1AlbK_y2gXVsjq3Vw4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hhyoi8noh
  api_key: '797163287459554'
  api_secret: AoduUAGnF1AlbK_y2gXVsjq3Vw4
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hhyoi8noh
  api_key: '797163287459554'
  api_secret: AoduUAGnF1AlbK_y2gXVsjq3Vw4
  enhance_image_tag: true
  static_image_support: false
